/**
 * Generated by Dalaran
 *   version: 0.0.19
 */
package com.ximalaya.openapi.admin.entity;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class PromotionItemDTO{

    @JsonProperty("item_id")
    @JsonInclude(Include.NON_NULL)
    private Long   itemId;

    @JsonProperty("item_name")
    @JsonInclude(Include.NON_NULL)
    private String itemName;

    @JsonProperty("unit_price")
    @JsonInclude(Include.NON_NULL)
    private String unitPrice;

    @JsonProperty("promotion_price")
    @JsonInclude(Include.NON_NULL)
    private String promotionPrice;
}