/**
 * Generated by Dalaran
 *   version: 0.0.62
 */
package com.ximalaya.openapi.admin.model.purchase;

public class ProjectChangeLog {

  /**
     * 日志类型：新增项目；项目增购
     */
  private String logType;
  /**
     * 变更参数
     */
  private String param;

  public ProjectChangeLog() {
  }

  public ProjectChangeLog(String logType, String param) {
    this.logType = logType;
    this.param = param;
  }

  public void setLogType(String logType) {
    this.logType = logType;
  }

  public String getLogType() {
    return this.logType;
  }

  public void setParam(String param) {
    this.param = param;
  }

  public String getParam() {
    return this.param;
  }

  @Override
  public String toString() {
    return "ProjectChangeLog(" +"logType=" + this.logType + ", " + "param=" + this.param + ")";
  }

  @Override
  public int hashCode() {
    int hash = 1;
    hash = 31 * hash + (this.logType == null ? 0 : this.logType.hashCode());
    hash = 31 * hash + (this.param == null ? 0 : this.param.hashCode());
    return hash;
  }

  @Override
  public boolean equals(Object other) {
    if (!(other instanceof ProjectChangeLog)) {
      return false;
    }
    ProjectChangeLog that = (ProjectChangeLog) other;
    if (this.logType == null) {
      if (that.logType != null)
        return false;
    } else if (!this.logType.equals(that.logType)) {
      return false;
    }
    if (this.param == null) {
      if (that.param != null)
        return false;
    } else if (!this.param.equals(that.param)) {
      return false;
    }
    return true;
  }
}